### ISSUE TITLE
setup.exe?

### ISSUE THREAD

**Issue by wspiking** [ZerionSoftware/iFormEsriIntegration#5]
Where is the setup.exe located in the download files per step 1 in the iFormBuilder.docx?

**Comment by benjaminray3** [comment]
Hi Bill,

The setup.exe file is located on the github website under releases. Github typically holds the source code and then you would build the executable file but to make it easier we have chosen to display the setup file ourselves.
 
Take a look at this link for the executable: https://github.com/ZerionSoftware/iFormEsriIntegration/releases <https://github.com/ZerionSoftware/iFormEsriIntegration/releases>

Thanks,
Ben
--
Ben Ray | Solutions Engineer
bray@iformbuilder.com <mailto:bray@iformbuilder.com>
Zerion Software Inc., iFormBuilder.com <http://www.iformbuilder.com/> 
O 866.937.4661 ext 7 <>02 <>  <>| M 717.220.4205 <>
Website <http://www.iformbuilder.com/> | Facebook <https://www.facebook.com/pages/iFormBuilder/143414062370953> | Twitter <https://twitter.com/iformbuilder> | +iFormBuilder <https://plus.google.com/+Iformbuilder/posts> | YouTube <https://www.youtube.com/user/iFormBuildermobile> | Skype <skype:benjamin.ray3>
This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited.
