### ISSUE TITLE
Config greyed out

### ISSUE THREAD

**Issue by afoxi911** [ZerionSoftware/iFormEsriIntegration#6]
any ideas why the config settings tool in the toolbar is greyed out after install?

**Comment by travisbutcher** [comment]
You need to Go to the Extensions and enable the iFormBuilder Extension
![image](https://cloud.githubusercontent.com/assets/1291442/9743151/b15d714c-5619-11e5-9533-6d966bc8b144.png)
![image](https://cloud.githubusercontent.com/assets/1291442/9743166/bce696d8-5619-11e5-8f4c-c6ef4ac6e30a.png)
